import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const products = [
  {
    name: 'White Linen Shirt',
    slug: 'white-linen-shirt',
    description: 'Classic shirt made from 100% premium linen. Perfect for warm days or a smart casual look.',
    price: 179.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
    category: 'clothing',
    inStock: true,
    stockCount: 45,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    name: 'Slim Fit Jeans',
    slug: 'slim-fit-jeans',
    description: 'Modern slim fit jeans in classic indigo wash. Stretch denim for all-day comfort.',
    price: 249.99,
    originalPrice: 329.99,
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
    category: 'clothing',
    inStock: true,
    stockCount: 62,
    rating: 4.3,
    reviewCount: 89,
  },
  {
    name: 'Oversized Wool Sweater',
    slug: 'oversized-wool-sweater',
    description: 'Cozy oversized sweater knitted from merino wool blend. Available in neutral tones.',
    price: 299.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80',
    category: 'clothing',
    inStock: true,
    stockCount: 30,
    rating: 4.7,
    reviewCount: 214,
  },
  {
    name: 'Floral Summer Dress',
    slug: 'floral-summer-dress',
    description: 'Light midi dress with a floral print. Features an adjustable waist tie.',
    price: 199.99,
    originalPrice: 269.99,
    imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=80',
    category: 'clothing',
    inStock: false,
    stockCount: 0,
    rating: 4.6,
    reviewCount: 177,
  },
  {
    name: 'Classic Leather Jacket',
    slug: 'classic-leather-jacket',
    description: 'Timeless biker-style jacket in genuine cow leather. A wardrobe staple that ages beautifully.',
    price: 899.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
    category: 'clothing',
    inStock: true,
    stockCount: 12,
    rating: 4.9,
    reviewCount: 56,
  },
  {
    name: 'White Canvas Sneakers',
    slug: 'white-canvas-sneakers',
    description: 'Minimalist white sneakers with a vulcanized sole. Goes with everything.',
    price: 219.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    category: 'footwear',
    inStock: true,
    stockCount: 88,
    rating: 4.4,
    reviewCount: 342,
  },
  {
    name: 'Suede Loafers',
    slug: 'suede-loafers',
    description: 'Premium suede penny loafers in cognac. Smart-casual shoe for any occasion.',
    price: 369.99,
    originalPrice: 449.99,
    imageUrl: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80',
    category: 'footwear',
    inStock: true,
    stockCount: 24,
    rating: 4.6,
    reviewCount: 93,
  },
  {
    name: 'Hiking Boots',
    slug: 'hiking-boots',
    description: 'Waterproof hiking boots with Gore-Tex lining. Ankle support and Vibram sole.',
    price: 599.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
    category: 'footwear',
    inStock: true,
    stockCount: 37,
    rating: 4.8,
    reviewCount: 201,
  },
  {
    name: 'Leather Sandals',
    slug: 'leather-sandals',
    description: 'Hand-crafted full-grain leather sandals with an adjustable buckle strap. Made in Portugal.',
    price: 269.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80',
    category: 'footwear',
    inStock: false,
    stockCount: 0,
    rating: 4.3,
    reviewCount: 67,
  },
  {
    name: 'Chelsea Boots',
    slug: 'chelsea-boots',
    description: 'Classic Chelsea boots in smooth black leather. Elastic side panels for easy on/off.',
    price: 449.99,
    originalPrice: 549.99,
    imageUrl: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80',
    category: 'footwear',
    inStock: true,
    stockCount: 19,
    rating: 4.5,
    reviewCount: 148,
  },
  {
    name: 'Bifold Leather Wallet',
    slug: 'bifold-leather-wallet',
    description: 'Slim bifold wallet in full-grain vegetable-tanned leather. 6 card slots.',
    price: 129.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594785?w=800&q=80',
    category: 'accessories',
    inStock: true,
    stockCount: 110,
    rating: 4.7,
    reviewCount: 289,
  },
  {
    name: 'Merino Wool Beanie',
    slug: 'merino-wool-beanie',
    description: 'Soft and warm beanie knitted from fine merino wool. One size fits all.',
    price: 89.99,
    originalPrice: 119.99,
    imageUrl: 'https://images.unsplash.com/photo-1510598969022-c4c6c5d05769?w=800&q=80',
    category: 'accessories',
    inStock: true,
    stockCount: 74,
    rating: 4.4,
    reviewCount: 156,
  },
  {
    name: 'Braided Leather Belt',
    slug: 'braided-leather-belt',
    description: 'Handwoven braided leather belt with a polished silver buckle.',
    price: 99.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    category: 'accessories',
    inStock: true,
    stockCount: 55,
    rating: 4.2,
    reviewCount: 82,
  },
  {
    name: 'Silk Square Scarf',
    slug: 'silk-square-scarf',
    description: 'Luxurious 100% silk twill scarf with an abstract geometric print. 70x70 cm.',
    price: 159.99,
    originalPrice: 219.99,
    imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80',
    category: 'accessories',
    inStock: true,
    stockCount: 28,
    rating: 4.6,
    reviewCount: 63,
  },
  {
    name: 'Aviator Sunglasses',
    slug: 'aviator-sunglasses',
    description: 'Classic metal-frame aviator sunglasses with polarized UV400 lenses.',
    price: 199.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80',
    category: 'accessories',
    inStock: true,
    stockCount: 41,
    rating: 4.5,
    reviewCount: 194,
  },
  {
    name: 'Wireless Headphones',
    slug: 'wireless-headphones',
    description: 'Over-ear wireless headphones with ANC. 30-hour battery, USB-C charging.',
    price: 699.99,
    originalPrice: 899.99,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    category: 'electronics',
    inStock: true,
    stockCount: 33,
    rating: 4.8,
    reviewCount: 427,
  },
  {
    name: 'MagSafe Wireless Charger',
    slug: 'magsafe-wireless-charger',
    description: 'Fast wireless charger with magnetic alignment. 15W for compatible devices.',
    price: 149.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&q=80',
    category: 'electronics',
    inStock: true,
    stockCount: 96,
    rating: 4.3,
    reviewCount: 312,
  },
  {
    name: 'Premium Phone Case',
    slug: 'premium-phone-case',
    description: 'Genuine leather phone case with card slot and shock-absorbing inner layer.',
    price: 119.99,
    originalPrice: 149.99,
    imageUrl: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&q=80',
    category: 'electronics',
    inStock: true,
    stockCount: 78,
    rating: 4.1,
    reviewCount: 145,
  },
  {
    name: 'Sport Smartwatch',
    slug: 'sport-smartwatch',
    description: 'GPS smartwatch with heart rate monitor and 7-day battery. IP68 waterproof.',
    price: 1199.99,
    originalPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    category: 'electronics',
    inStock: true,
    stockCount: 21,
    rating: 4.7,
    reviewCount: 288,
  },
  {
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    description: 'Waterproof portable speaker with 360 sound and 20-hour playtime.',
    price: 349.99,
    originalPrice: 429.99,
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
    category: 'electronics',
    inStock: false,
    stockCount: 0,
    rating: 4.6,
    reviewCount: 193,
  },
]

async function main() {
  console.log('Seeding database...')
  await prisma.product.deleteMany()
  for (const product of products) {
    await prisma.product.create({ data: product })
  }
  console.log(`Seeded ${products.length} products.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
